DROP TABLE IF EXISTS CUSTOMERS;
DROP TABLE IF EXISTS PRODUCTS;
DROP TABLE IF EXISTS EVENTS;
DROP TABLE IF EXISTS HEROS;

DROP TABLE IF EXISTS PANELS;
CREATE TABLE  PANELS
(
PANELSID INTEGER PRIMARY KEY,
BRAND varchar(64),
SIZE  varchar(16),
TYPE  varchar(16),
MODELNO varchar(64)
);

INSERT INTO PANELS (BRAND, SIZE, TYPE, MODELNO) 
VALUES ('CANADIAN', '270W', 'MONO', 'CS6K-M'),
('CANADIAN', '270W', 'POLY', 'CS6P-P'),
('TIANWEI', '250W', 'POLY', 'TW250L60-FA'),
('TIANWEI', '250W', 'POLY', 'MWT--TW250B60-PA'),
('Q-CELL', '270W', 'POLY', 'Q.PLUS-G4 170'),
('Q-CELL', '255W', 'POLY', 'Q.PRO-G4');

DROP TABLE IF EXISTS INVERTERS;
CREATE TABLE INVERTERS
(
INVERTERSID INTEGER PRIMARY KEY,
BRAND varchar(64),
SIZE varchar(16),
TYPE varchar(16),
MODELNO varchar(64)
);

INSERT INTO INVERTERS (BRAND, SIZE, TYPE, MODELNO) 
VALUES ('SMA','3KW', 'DUAL MPPT', 'SUNNYBOY 3000TL-21'),
('SMA','5KW', 'DUAL MPPT', 'SUNNYBOY 5000TL-21'),
('GROWATT','3KW', 'SINGLE MPPT', 'GROWATT 3000TL'),
('GROWATT','5KW', 'DUAL MPPT', 'GROWATT 5000MTL'),
('DELTA','3KW', 'SINGLE MPPT', 'RPI H3 3KW'),
('DELTA','5KW', 'DUAL MPPT', 'RPI H5A 5KW');



